PREFIX product: <https://w3id.org/product#>
PREFIX props: <https://w3id.org/props#>
PREFIX lbs:   <http://test/lbs/>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>	
PREFIX ont:  <http://test/ontology/>
PREFIX tci:   <http://test/tci/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

	### SELECT Output graph that is needed to visualize in web application or Exicute!! ###


SELECT ?Element_ID ?length ?PrimaryTCIs ?TCIsCount ?SecondaryTCIs ?2TCIsCount ?Location ?PlannedStartDate ?PlannedEndDate ?ActualStartDate ?ActualEndDate ?ProgressDate ?ProgressCompletion

WHERE {GRAPH <http://localhost:3030/TCI-Demo/data/Combined> 
{
?Revitinst a product:Wall ;
	props:Element_ID ?Element_ID ;
	props:length ?length ;
	tci:hasTCIs ?PrimaryTCIs;
	tci:hassecTCIs ?SecondaryTCIs .
	
?1Countprop tci:iscounting ?PrimaryTCIs .
?Revitinst ?1Countprop ?TCIsCount .
?2Countprop tci:iscounting ?SecondaryTCIs .
?Revitinst ?2Countprop ?2TCIsCount .
        
  ?VICOinst a lbs:CompLoid ;
	props:Element_ID ?Element_ID ;
	lbs:hasLocation ?Location;
	lbs:taskPlannedStartDate ?PlannedStartDate;
	lbs:taskPlannedEndDate ?PlannedEndDate;
	lbs:taskActualStartDate ?ActualStartDate;
	lbs:taskActualEndDate ?ActualEndDate;
	lbs:taskProgressDate ?ProgressDate ;
	lbs:taskProgressCompletion ?ProgressCompletion .
     
FILTER (?VICOinst != ?Revitinst)
}}